spring:
  cache:
    type: redis
    cache-names: courseDetails
    redis:
      time-to-live: ${COURSE_CACHE_TTL:10m}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/course_management}
    username: ${SPRING_DATASOURCE_USERNAME:course_user}
    password: ${SPRING_DATASOURCE_PASSWORD:course_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8080
